# coding: utf-8

# flake8: noqa
"""
    Issue Tracker

    This application implements a very simple issue tracker.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from client.models.task import Task
from client.models.user import User
