# coding: utf-8

"""
    Issue Tracker

    This application implements a very simple issue tracker.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import client
from client.models.user import User  # noqa: E501
from client.rest import ApiException


class TestUser(unittest.TestCase):
    """User unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUser(self):
        """Test User"""
        # FIXME: construct object with mandatory attributes with example values
        # model = client.models.user.User()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
