# coding: utf-8

"""
    Issue Tracker

    This application implements a very simple issue tracker.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import client
from client.api.default_api import DefaultApi  # noqa: E501
from client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_task(self):
        """Test case for create_task

        Creates a 'Task' object.  # noqa: E501
        """
        pass

    def test_list_tasks(self):
        """Test case for list_tasks

        Lists the tasks  # noqa: E501
        """
        pass

    def test_update_task(self):
        """Test case for update_task

        Updates the details for a task.  # noqa: E501
        """
        pass

    def test_view_task(self):
        """Test case for view_task

        Gets the details for a task.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
