books_body = {'books': [{'category': 'reference', 'author': 'Nigel Rees', 'title': 'Sayings of the Century', 'price': 8.95, 'id': 1},
                        {'category': 'fiction', 'author': 'Evelyn Waugh', 'title': 'Sword of Honour', 'price': 12.99, 'id': 2},
                        {'category': 'fiction', 'author': 'Herman Melville', 'title': 'Moby Dick', 'isbn': '0-553-21311-3', 'price': 8.99, 'id': 3},
                        {'category': 'fiction', 'author': 'J. R. R. Tolkien', 'title': 'The Lord of the Rings', 'isbn': '0-395-19395-8', 'price': 22.99, 'id': 4}],
              'services': {'delivery': {'servicegroup': 1000, 'description': 'Next day delivery in local town', 'active': True, 'price': 5},
                           'bookbinding': {'servicegroup': 1001, 'description': 'Printing and assembling book in A5 format', 'active': True, 'price': 154.99},
                           'restoration': {'servicegroup': 1002, 'description': 'Various restoration methods', 'active': False,
                                           'methods': [{'description': 'Checmical cleaning', 'price': 46}, {'description': 'Pressing pages damaged by moisture', 'price': 24.5},
                                                       {'description': 'Rebinding torn book', 'price': 99.49}]}}, 'filters': {'price': 10, 'category': 'fiction', 'no filters': 'nofilters'},
              'closed message': 'Store is closed', 'tags': ['a', 'b', 'c', 'd', 'e']}

patient_body = \
    {'aliasName': 'EBZQQ', 'bloodGroupId': 54, 'bloodGroupIdStr': '54', 'customerPatientIds': None, 'deceased': None, 'deceasedOn': None, 'dob': '1947-05-11', 'documents': None,
     'email': 'jasonsmith@example.com', 'firstName': 'Mary', 'genderId': 9, 'genderIdStr': '9', 'insurances': None, 'isExpanded': False, 'labId': 0, 'lastName': 'Campbell',
     'maidenName': 'Cortez', 'maritalStatusId': 9, 'maritalStatusIdStr': '9', 'medicalRecordNumber': 0, 'middleName': 'Joshua', 'notes': 'Hear other father mother station thousand food.',
     'orders': None, 'patientAddresses': [
        {'addressLine1': '', 'addressLine2': '', 'city': '', 'countryId': 0, 'id': None, 'labId': None, 'mdCountry': None, 'mdState': None, 'mgPrimaryAddresseeName': None,
         'mgPrimaryRelationship': None, 'mgSecondaryAddresseeName': None, 'mgSecondaryRelationship': None, 'patient': None, 'patientId': 0, 'primaryAddress': True, 'state': '', 'stateId': 0,
         'zipCode': ''}], 'patientEthnicities': [{'ethnicityId': 244}], 'patientEthnicitiesArr': [244], 'patientIdentifier': None, 'patientRaces': [{'raceId': 12}, {'raceId': 10}, {'raceId': 9}],
     'patientRacesArr': [12, 10, 9],
     'patientSpecialConditions': [{'specialConditionId': 1}], 'patientSpecialConditionsArr': [1], 'primaryLanguageId': 189, 'primaryLanguageIdStr': '189',
     'primaryPhone': '(+1) 450-962-7354', 'primaryPhoneExt': None, 'primaryPhoneTypeId': 6, 'qcs': None, 'readonly': False, 'relatedPerson': False, 'relatedPersonsForPatientId': None,
     'relatedPersonsForSema4Id': None, 'secondaryLanguageId': 230, 'secondaryLanguageIdStr': '230', 'secondaryPhone': '5554751476', 'secondaryPhoneExt': None, 'secondaryPhoneTypeId': 6,
     'ssn': '717925776', 'ssn1': None, 'ssn2': None, 'ssn3': None, 'studyIdentifier': '8770635', 'suffix': 'DDS', 'title': 'Jr.'}

search_body = \
    {'content': [
        {'orderId': 1345993, 'accessionId': 'AC204817', 'orderStatus': None, 'patientId': 1895377, 'deceased': None, 'name': 'Test, Bug ', 'firstName': 'Bug', 'lastName': 'Test', 'middleName': None,
         'mrn': None, 'aliasName': None, 'dob': '2012-02-02', 'email': None, 'genderId': 8, 'genderLabel': 'Female', 'genderMnemonic': 'F', 'custOrderId': None, 'locationId': None,
         'locationName': None,
         'providerId': None, 'provFirstName': None, 'provLastName': None, 'provMiddleName': None, 'practiceId': None, 'practiceName': None, 'primaryReferrer': None, 'phone': '',
         'patientAddressL1': None,
         'patientAddressL2': None, 'orderCreationDate': '2020-08-07T13:54:38', 'status': True},
        {'orderId': 1345698, 'accessionId': 'AC204471', 'orderStatus': None, 'patientId': 1895346, 'deceased': None, 'name': 'Test, Db ', 'firstName': 'Db', 'lastName': 'Test', 'middleName': None,
         'mrn': None, 'aliasName': None, 'dob': '', 'email': None, 'genderId': 10, 'genderLabel': 'Unknown/Not Reported', 'genderMnemonic': 'U', 'custOrderId': None, 'locationId': None,
         'locationName': None, 'providerId': None, 'provFirstName': None, 'provLastName': None, 'provMiddleName': None, 'practiceId': None, 'practiceName': None, 'primaryReferrer': None,
         'phone': None,
         'patientAddressL1': '', 'patientAddressL2': None, 'orderCreationDate': '2020-06-03T14:04:08', 'status': True},
        {'orderId': 1345706, 'accessionId': 'AC204479', 'orderStatus': None, 'patientId': 1895343, 'deceased': None, 'name': 'Test, Dbo ', 'firstName': 'Dbo', 'lastName': 'Test', 'middleName': '',
         'mrn': None, 'aliasName': None, 'dob': '2012-12-12', 'email': 'test@yahoo.com', 'genderId': 8, 'genderLabel': 'Female', 'genderMnemonic': 'F', 'custOrderId': None, 'locationId': None,
         'locationName': None, 'providerId': None, 'provFirstName': None, 'provLastName': None, 'provMiddleName': None, 'practiceId': None, 'practiceName': None, 'primaryReferrer': None,
         'phone': '(+1) 111-111-1111', 'patientAddressL1': '12340 Boggy Creek Road', 'patientAddressL2': ',Orlando,Florida,United States, 32824', 'orderCreationDate': '2020-06-04T06:42:58',
         'status': True},
        {'orderId': 1345839, 'accessionId': 'AC204638', 'orderStatus': None, 'patientId': 1895369, 'deceased': None, 'name': 'Test, Dxfc T', 'firstName': 'Dxfc', 'lastName': 'Test', 'middleName': 'T',
         'mrn': None, 'aliasName': None, 'dob': '2012-02-02', 'email': 'dfcv@comcast.net', 'genderId': 7, 'genderLabel': 'Ambiguous/Undetermined', 'genderMnemonic': 'A', 'custOrderId': None,
         'locationId': None, 'locationName': None, 'providerId': None, 'provFirstName': None, 'provLastName': None, 'provMiddleName': None, 'practiceId': None, 'practiceName': None,
         'primaryReferrer': None, 'phone': '(+1) 111-111-1111', 'patientAddressL1': '', 'patientAddressL2': None, 'orderCreationDate': '2020-06-16T06:01:53', 'status': True},
        {'orderId': 1345734, 'accessionId': 'AC204510', 'orderStatus': None, 'patientId': 355, 'deceased': None, 'name': 'Test, Ecshemo ', 'firstName': 'Ecshemo', 'lastName': 'Test',
         'middleName': None,
         'mrn': None, 'aliasName': None, 'dob': '1980-01-01', 'email': None, 'genderId': 9, 'genderLabel': 'Male', 'genderMnemonic': 'M', 'custOrderId': None, 'locationId': None, 'locationName': None,
         'providerId': None, 'provFirstName': None, 'provLastName': None, 'provMiddleName': None, 'practiceId': 2, 'practiceName': 'practice name 2', 'primaryReferrer': None, 'phone': None,
         'patientAddressL1': '', 'patientAddressL2': ',New York,New York,United States, ', 'orderCreationDate': '2020-06-04T09:54:01', 'status': True},
        {'orderId': 1345699, 'accessionId': 'AC204472', 'orderStatus': None, 'patientId': 1895153, 'deceased': None, 'name': 'Test, Ecshemo ', 'firstName': 'Ecshemo', 'lastName': 'Test',
         'middleName': None, 'mrn': None, 'aliasName': None, 'dob': '', 'email': None, 'genderId': 10, 'genderLabel': 'Unknown/Not Reported', 'genderMnemonic': 'U', 'custOrderId': None,
         'locationId': None, 'locationName': None, 'providerId': None, 'provFirstName': None, 'provLastName': None, 'provMiddleName': None, 'practiceId': None, 'practiceName': None,
         'primaryReferrer': None, 'phone': None, 'patientAddressL1': '', 'patientAddressL2': None, 'orderCreationDate': '2020-06-03T14:04:28', 'status': True},
        {'orderId': None, 'accessionId': None, 'orderStatus': None, 'patientId': 1895171, 'deceased': None, 'name': 'Test, Ecshemo ', 'firstName': 'Ecshemo', 'lastName': 'Test', 'middleName': None,
         'mrn': None, 'aliasName': None, 'dob': '', 'email': None, 'genderId': 10, 'genderLabel': 'Unknown/Not Reported', 'genderMnemonic': 'U', 'custOrderId': None, 'locationId': None,
         'locationName': None, 'providerId': None, 'provFirstName': None, 'provLastName': None, 'provMiddleName': None, 'practiceId': None, 'practiceName': None, 'primaryReferrer': None,
         'phone': None,
         'patientAddressL1': '', 'patientAddressL2': None, 'orderCreationDate': None, 'status': True},
        {'orderId': 1345860, 'accessionId': 'AC204666', 'orderStatus': None, 'patientId': 1895371, 'deceased': None, 'name': 'Test, Erfg ', 'firstName': 'Erfg', 'lastName': 'Test', 'middleName': None,
         'mrn': None, 'aliasName': None, 'dob': '', 'email': None, 'genderId': 10, 'genderLabel': 'Unknown/Not Reported', 'genderMnemonic': 'U', 'custOrderId': None, 'locationId': None,
         'locationName': None, 'providerId': None, 'provFirstName': None, 'provLastName': None, 'provMiddleName': None, 'practiceId': None, 'practiceName': None, 'primaryReferrer': None,
         'phone': None,
         'patientAddressL1': '', 'patientAddressL2': None, 'orderCreationDate': '2020-06-19T06:34:38', 'status': True},
        {'orderId': 1345850, 'accessionId': 'AC204654', 'orderStatus': None, 'patientId': 3, 'deceased': None, 'name': 'Test, Feb18 ', 'firstName': 'Feb18', 'lastName': 'Test', 'middleName': None,
         'mrn': None, 'aliasName': None, 'dob': '2002-02-02', 'email': '', 'genderId': 8, 'genderLabel': 'Female', 'genderMnemonic': 'F', 'custOrderId': None, 'locationId': 1,
         'locationName': 'location name 1', 'providerId': 611025, 'provFirstName': 'first name 1', 'provLastName': 'last name 1', 'provMiddleName': None, 'practiceId': 1,
         'practiceName': 'practice name 1', 'primaryReferrer': True, 'phone': '', 'patientAddressL1': '200 Park Avenue South', 'patientAddressL2': ',New York,New York,United States, 10003',
         'orderCreationDate': '2020-06-18T12:18:11', 'status': True},
        {'orderId': None, 'accessionId': None, 'orderStatus': None, 'patientId': 521, 'deceased': None, 'name': 'Test, Forfun ', 'firstName': 'Forfun', 'lastName': 'Test', 'middleName': None,
         'mrn': None,
         'aliasName': None, 'dob': '2011-10-10', 'email': '', 'genderId': 9, 'genderLabel': 'Male', 'genderMnemonic': 'M', 'custOrderId': None, 'locationId': None, 'locationName': None,
         'providerId': None, 'provFirstName': None, 'provLastName': None, 'provMiddleName': None, 'practiceId': None, 'practiceName': None, 'primaryReferrer': None, 'phone': '',
         'patientAddressL1': '',
         'patientAddressL2': None, 'orderCreationDate': None, 'status': True},
        {'orderId': None, 'accessionId': None, 'orderStatus': None, 'patientId': 1895173, 'deceased': None, 'name': 'Test, Forfun ', 'firstName': 'Forfun', 'lastName': 'Test', 'middleName': None,
         'mrn': None, 'aliasName': None, 'dob': '2010-11-11', 'email': None, 'genderId': 9, 'genderLabel': 'Male', 'genderMnemonic': 'M', 'custOrderId': None, 'locationId': None, 'locationName': None,
         'providerId': None, 'provFirstName': None, 'provLastName': None, 'provMiddleName': None, 'practiceId': None, 'practiceName': None, 'primaryReferrer': None, 'phone': '(+1) 111-111-1111',
         'patientAddressL1': '', 'patientAddressL2': None, 'orderCreationDate': None, 'status': True},
        {'orderId': None, 'accessionId': None, 'orderStatus': None, 'patientId': 359, 'deceased': None, 'name': 'Test, Hemowecs ', 'firstName': 'Hemowecs', 'lastName': 'Test', 'middleName': None,
         'mrn': None, 'aliasName': None, 'dob': '1980-01-01', 'email': None, 'genderId': 9, 'genderLabel': 'Male', 'genderMnemonic': 'M', 'custOrderId': None, 'locationId': None, 'locationName': None,
         'providerId': None, 'provFirstName': None, 'provLastName': None, 'provMiddleName': None, 'practiceId': None, 'practiceName': None, 'primaryReferrer': None, 'phone': None,
         'patientAddressL1': None, 'patientAddressL2': None, 'orderCreationDate': None, 'status': True}], 'number': 0, 'size': 12, 'totalElements': 88, 'last': False, 'totalPages': 8, 'first': True,
        'numberOfElements': 12}

dict_insurances = [
    {'id': 144, 'name': ' United HealthCare', 'addressLine1': 'P.O. BOX 740800', 'addressLine2': None, 'city': 'ATLANTA', 'state': 'GA', 'stateId': None, 'zipCode': '30374-0800',
     'countryId': None,
     'phoneType': None, 'phone': None, 'phoneExt': None},
    {'id': 145, 'name': '*Template Commerical', 'addressLine1': None, 'addressLine2': None, 'city': None, 'state': None, 'stateId': None, 'zipCode': None, 'countryId': None, 'phoneType': None,
     'phone': None, 'phoneExt': None}]
